name: leaves
provider:
  _target_: data.DatasetProvider
  dataset_class:
    _target_: hydra.utils.get_class
    path: data.LeavesDataset
  feature_provider: ${feature_provider}
  data_root: ${hydra:runtime.cwd}/datasets/leaves
  resize: ${resize}
